# Generated by Django 4.0.5 on 2022-07-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'unique_together': {('client_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=500)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'unique_together': {('client_org', 'number')},
            },
        ),
    ]
