# Generated by Django 4.0.5 on 2022-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fraud_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
