# Generated by Django 4.0.5 on 2022-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bill_fraud_score_bill_service_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sum',
            field=models.FloatField(),
        ),
    ]
